name: Gut

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  gut:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Make gut.sh executable
        run: chmod +x ./Sviluppo/Godot/gut.sh
        
      - name: Gut (gut.sh)
        run: ./Sviluppo/Godot/gut.sh
